<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Invoice #{{ $invoice->invoice_no }}</title>
<style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f3f4f6; margin: 0; padding: 0; }
    .wrapper { max-width: 600px; margin: 0 auto; background: #fff; }
    .header { background: linear-gradient(135deg, #065f46, #059669); padding: 32px 40px; }
    .header h1 { color: #fff; font-size: 24px; margin: 0 0 4px; font-weight: 700; }
    .header p { color: #a7f3d0; margin: 0; font-size: 14px; }
    .body { padding: 32px 40px; }
    .greeting { font-size: 16px; color: #374151; margin-bottom: 16px; }
    .invoice-box { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 12px; padding: 20px; margin-bottom: 24px; }
    .invoice-row { display: flex; justify-content: space-between; margin-bottom: 8px; font-size: 14px; }
    .invoice-row .label { color: #6b7280; }
    .invoice-row .val { color: #111827; font-weight: 600; }
    .total-row { border-top: 2px solid #059669; padding-top: 12px; margin-top: 8px; }
    .total-row .val { color: #059669; font-size: 18px; }
    .message { font-size: 14px; color: #4b5563; line-height: 1.7; margin-bottom: 24px; }
    .cta { background: #059669; color: #fff; text-decoration: none; padding: 12px 28px; border-radius: 8px; font-weight: 600; font-size: 14px; display: inline-block; }
    .divider { border: none; border-top: 1px solid #e5e7eb; margin: 24px 0; }
    .footer { padding: 20px 40px; background: #f9fafb; text-align: center; }
    .footer p { font-size: 12px; color: #9ca3af; margin: 4px 0; }
    .footer strong { color: #065f46; }
</style>
</head>
<body>
<div class="wrapper">

    <div class="header">
        <h1>📄 Invoice from {{ $invoice->client->business_name }}</h1>
        <p>Invoice #{{ $invoice->invoice_no }} · {{ $invoice->invoice_date->format('d M Y') }}</p>
    </div>

    <div class="body">
        <p class="greeting">Dear <strong>{{ $invoice->customer->name }}</strong>,</p>

        <p class="message">
            Please find attached your invoice from <strong>{{ $invoice->client->business_name }}</strong>.
            The PDF invoice is attached to this email for your records.
        </p>

        <div class="invoice-box">
            <div class="invoice-row">
                <span class="label">Invoice Number</span>
                <span class="val">{{ $invoice->invoice_no }}</span>
            </div>
            <div class="invoice-row">
                <span class="label">Invoice Date</span>
                <span class="val">{{ $invoice->invoice_date->format('d M Y') }}</span>
            </div>
            @if($invoice->due_date)
            <div class="invoice-row">
                <span class="label">Due Date</span>
                <span class="val">{{ $invoice->due_date->format('d M Y') }}</span>
            </div>
            @endif
            <div class="invoice-row">
                <span class="label">Subtotal</span>
                <span class="val">Rs {{ number_format($invoice->subtotal, 2) }}</span>
            </div>
            <div class="invoice-row">
                <span class="label">GST ({{ $invoice->client->province }})</span>
                <span class="val">Rs {{ number_format($invoice->gst_amount, 2) }}</span>
            </div>
            <div class="invoice-row total-row">
                <span class="label" style="font-weight:700;color:#111827;">Grand Total</span>
                <span class="val">Rs {{ number_format($invoice->total, 2) }}</span>
            </div>
        </div>

        <p class="message">
            If you have any questions about this invoice, please don't hesitate to contact us at
            <strong>{{ $invoice->client->email ?? $invoice->client->phone }}</strong>.
        </p>

        @if($invoice->notes)
        <p class="message" style="background:#fef3c7;border-left:3px solid #f59e0b;padding:12px 16px;border-radius:6px;">
            <strong>Note:</strong> {{ $invoice->notes }}
        </p>
        @endif

        <hr class="divider">
        <p class="message" style="font-size:12px;color:#9ca3af;">
            This invoice was generated by GST Invoice Portal · NTN: {{ $invoice->client->ntn ?? 'N/A' }} · {{ $invoice->client->province }}
        </p>
    </div>

    <div class="footer">
        <p><strong>{{ $invoice->client->business_name }}</strong></p>
        <p>{{ $invoice->client->address }}</p>
        @if($invoice->client->phone)<p>📞 {{ $invoice->client->phone }}</p>@endif
    </div>

</div>
</body>
</html>
